services:
  - type: web
    name: customer-churn-api
    runtime: docker
    repo: https://github.com/kvskarthikreddy/Customer_Churn_Prediction---with-SQL-Database
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        value: postgresql://customer_churn_db_user:MNMNaERwcaBxxL1XLiknwlNuvwk75jFU@dpg-cv90tr8gph6c73c44st0-a.oregon-postgres.render.com/customer_churn_db
      - key: PORT
        value: 8000
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
